# Test Sparse AP

In [1]:
import numpy as np
from scipy.sparse import csr_matrix

data = np.array([1.,2,3,4,5,6,7,8,9])
rows = np.array([0,0,1,1, 2,3,3,4,4])
cols = np.array([0,1,1,2,2,2,3,3,4])
data = np.append(data, 3)
rows = np.append(rows, 4)
cols = np.append(cols, 2)
kk = np.argwhere(rows == cols).T[0]
n = 5
sm = csr_matrix((data, (rows, cols)), shape=(n, n))
sm.toarray()

array([[ 1.,  2.,  0.,  0.,  0.],
       [ 0.,  3.,  4.,  0.,  0.],
       [ 0.,  0.,  5.,  0.,  0.],
       [ 0.,  0.,  6.,  7.,  0.],
       [ 0.,  0.,  3.,  8.,  9.]])

In [2]:
print rows
row_indptr = np.insert(np.where(np.diff(rows) > 0)[0] + 1, 0, 0)
if row_indptr[-1] != data.shape[0]:
    row_indptr = np.append(row_indptr, data.shape[0])

[0 0 1 1 2 3 3 4 4 4]


In [25]:
print data
sm = csr_matrix((data, (rows, cols)), shape=(n, n))
sm.toarray()

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.  3.]


array([[ 1.,  2.,  0.,  0.,  0.],
       [ 0.,  3.,  4.,  0.,  0.],
       [ 0.,  0.,  5.,  0.,  0.],
       [ 0.,  0.,  6.,  7.,  0.],
       [ 0.,  0.,  3.,  8.,  9.]])

In [40]:
z = np.array([0,1,2,3])
np.in1d(z, [0,1])

array([ True,  True, False, False], dtype=bool)

In [87]:
from icing.externals import sparseMatrixPrepare
reload(sparseMatrixPrepare)
a,b,c,d,e,f = sparseMatrixPrepare.rmSingleSamples(rows, cols, data, n)

[2] [4] [3.0]
[2] [4] [ 3.]
[0] [1] [2.0]
[0] [1] [ 2.]
[0, 4] [1, 2] [2.0, 3.0]
[0 4] [1 2] [ 2.  3.]


In [88]:
sm = csr_matrix((c, (a, b)), shape=(f, f))
sm.toarray()

array([[ 1.,  2.,  0.,  0.,  0.],
       [ 2.,  3.,  4.,  0.,  0.],
       [ 0.,  0.,  5.,  0.,  6.],
       [ 0.,  0.,  6.,  7.,  0.],
       [ 0.,  0.,  3.,  8.,  9.]])

In [ ]:
sm = csr_matrix((data, (rows, cols)), shape=(n, n))
sm.toarray()

In [ ]:
np.max(sm.toarray(), axis=1)

In [ ]:
S = sm.toarray()

In [ ]:
tmp = S
ind = np.arange(S.shape[0])

In [ ]:
I = np.argmax(tmp, axis=1)
Y = tmp[ind, I]  # np.max(A + S, axis=1)
tmp[ind, I] = -np.inf
Y2 = np.max(tmp, axis=1)

# tmp = Rnew
np.subtract(S, Y[:, None], tmp)
tmp[ind, I] = S[ind, I] - Y2

In [ ]:
tmp

In [ ]:
sm = csr_matrix((data, (rows, cols)), shape=(n, n))
sm.toarray()

In [ ]:
from icing.externals import sparse_affinity_propagation as sap
data

In [ ]:
reload(sap)
data1 = data.copy()
sap._sparse_sum_update(data1, rows, kk)
data1

In [ ]:
data[kk] += 3

In [ ]:
kk

In [ ]:
data

In [ ]:
sm.toarray()