# Test Sparse AP

In [1]:
import numpy as np
from scipy.sparse import csr_matrix

data = np.array([1.,2,3,4])
rows = np.array([0,0,1,1])
cols = np.array([0,1,1,2])
n = 5
sm = csr_matrix((data, (rows, cols)), shape=(n, n))
sm.toarray()

array([[ 1.,  2.,  0.,  0.,  0.],
       [ 0.,  3.,  4.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [2]:
preferences = np.array([.1, .2, .3, .4, .5])
idx = np.where(rows == cols)[0]
data[idx] = preferences[rows[idx]]

In [3]:
mask = np.ones(preferences.shape, dtype=bool)
mask[rows[idx]] = False

In [4]:
diag_other = np.argwhere(mask).T[0]

In [5]:
rows = np.concatenate((rows, diag_other))
cols = np.concatenate((cols, diag_other))
data = np.concatenate((data, preferences[mask]))

In [6]:
sm = csr_matrix((data, (rows, cols)), shape=(n, n))
sm.toarray()

array([[ 0.1,  2. ,  0. ,  0. ,  0. ],
       [ 0. ,  0.2,  4. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.3,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0.4,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.5]])

In [7]:
# find rows that have only one element
unique, counts = np.unique(rows, return_counts=True)
rows_one_element = unique[counts == 1]

In [8]:
rows_one_element

array([2, 3, 4])

In [9]:
from pysapc import sparseAP_cy

In [75]:
idx = np.array([0,1])
print rows
print cols
print data

[0 0 1 1 2 3 4]
[0 1 1 2 2 3 4]
[ 0.1  2.   0.2  4.   0.3  0.4  0.5]


In [78]:
mask = np.ones(rows.shape[0], dtype=bool)
mask[idx] = False
idx_to_remove = np.logical_or(rows == cols, mask)
print rows == cols
print mask
print idx_to_remove

[ True False  True False  True  True  True]
[False False  True  True  True  True  True]
[ True False  True  True  True  True  True]


array([0, 0, 1, 1, 2, 3, 4])

In [60]:
mask = np.zeros(rows.shape[0], dtype=bool)
mask[idx] = True
print mask
print rows
np.where(rows, idx, 0)

[ True  True False False False False False]
[0 0 1 1 2 3 4]


ValueError: operands could not be broadcast together with shapes (7,) (2,) () 

In [33]:
mask = np.ones(preferences.shape, dtype=bool)
mask[np.array([2,3])] = False
np.arange(preferences.shape[0])[mask]

array([0, 1, 4])